use super::key::KeyType;

#[derive(PartialEq)]
pub enum KeyCode {
    Nul,
    Soh,
    Stx,
    Etx,
    Eot,
    Enq,
    Ack,
    Bell,
    Backspace,
    Tab,
    LineFeed,
    Vt,
    Ff,
    CarriageReturn,
    So,
    Si,
    Dle,
    Dc1,
    Dc2,
    Dc3,
    Dc4,
    Nak,
    Syn,
    Etb,
    Can,
    Em,
    Sub,
    Esc,
    Fs,
    Gs,
    Rs,
    Us,
    Space,
    Exclamation,
    DoubleQuote,
    Hash,
    Dollar,
    Percent,
    Ampersand,
    Quote,
    LeftParenthesis,
    RightParenthesis,
    Asterisk,
    Plus,
    Comma,
    Minus,
    Period,
    Slash,
    Zero,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,
    Colon,
    Semicolon,
    LessThan,
    Equal,
    GreaterThan,
    Question,
    At,
    UpperA,
    UpperB,
    UpperC,
    UpperD,
    UpperE,
    UpperF,
    UpperG,
    UpperH,
    UpperI,
    UpperJ,
    UpperK,
    UpperL,
    UpperM,
    UpperN,
    UpperO,
    UpperP,
    UpperQ,
    UpperR,
    UpperS,
    UpperT,
    UpperU,
    UpperV,
    UpperW,
    UpperX,
    UpperY,
    UpperZ,
    LeftBracket,
    Backslash,
    RightBracket,
    Caret,
    Underscore,
    Grave,
    LowerA,
    LowerB,
    LowerC,
    LowerD,
    LowerE,
    LowerF,
    LowerG,
    LowerH,
    LowerI,
    LowerJ,
    LowerK,
    LowerL,
    LowerM,
    LowerN,
    LowerO,
    LowerP,
    LowerQ,
    LowerR,
    LowerS,
    LowerT,
    LowerU,
    LowerV,
    LowerW,
    LowerX,
    LowerY,
    LowerZ,
    LeftBrace,
    Pipe,
    RightBrace,
    Tilde,
    Del,
}

impl KeyCode {
    pub fn to_key_type(&self) -> KeyType {
        let ascii_byte = self.to_character().get(0).cloned().unwrap_or(0);
        KeyType::char_to_key_type(ascii_byte)
    }

    pub fn to_character(&self) -> Vec<u8> {
        match self {
            KeyCode::Nul => b"\x00".to_vec(),
            KeyCode::Soh => b"\x01".to_vec(),
            KeyCode::Stx => b"\x02".to_vec(),
            KeyCode::Etx => b"\x03".to_vec(),
            KeyCode::Eot => b"\x04".to_vec(),
            KeyCode::Enq => b"\x05".to_vec(),
            KeyCode::Ack => b"\x06".to_vec(),
            KeyCode::Bell => b"\x07".to_vec(),
            KeyCode::Backspace => b"\x08".to_vec(),
            KeyCode::Tab => b"\x09".to_vec(),
            KeyCode::LineFeed => b"\x0A".to_vec(),
            KeyCode::Vt => b"\x0B".to_vec(),
            KeyCode::Ff => b"\x0C".to_vec(),
            KeyCode::CarriageReturn => b"\x0D".to_vec(),
            KeyCode::So => b"\x0E".to_vec(),
            KeyCode::Si => b"\x0F".to_vec(),
            KeyCode::Dle => b"\x10".to_vec(),
            KeyCode::Dc1 => b"\x11".to_vec(),
            KeyCode::Dc2 => b"\x12".to_vec(),
            KeyCode::Dc3 => b"\x13".to_vec(),
            KeyCode::Dc4 => b"\x14".to_vec(),
            KeyCode::Nak => b"\x15".to_vec(),
            KeyCode::Syn => b"\x16".to_vec(),
            KeyCode::Etb => b"\x17".to_vec(),
            KeyCode::Can => b"\x18".to_vec(),
            KeyCode::Em => b"\x19".to_vec(),
            KeyCode::Sub => b"\x1A".to_vec(),
            KeyCode::Esc => b"\x1B".to_vec(),
            KeyCode::Fs => b"\x1C".to_vec(),
            KeyCode::Gs => b"\x1D".to_vec(),
            KeyCode::Rs => b"\x1E".to_vec(),
            KeyCode::Us => b"\x1F".to_vec(),
            KeyCode::Space => b" ".to_vec(),
            KeyCode::Exclamation => b"!".to_vec(),
            KeyCode::DoubleQuote => b"\"".to_vec(),
            KeyCode::Hash => b"#".to_vec(),
            KeyCode::Dollar => b"$".to_vec(),
            KeyCode::Percent => b"%".to_vec(),
            KeyCode::Ampersand => b"&".to_vec(),
            KeyCode::Quote => b"'".to_vec(),
            KeyCode::LeftParenthesis => b"(".to_vec(),
            KeyCode::RightParenthesis => b")".to_vec(),
            KeyCode::Asterisk => b"*".to_vec(),
            KeyCode::Plus => b"+".to_vec(),
            KeyCode::Comma => b",".to_vec(),
            KeyCode::Minus => b"-".to_vec(),
            KeyCode::Period => b".".to_vec(),
            KeyCode::Slash => b"/".to_vec(),
            KeyCode::Zero => b"0".to_vec(),
            KeyCode::One => b"1".to_vec(),
            KeyCode::Two => b"2".to_vec(),
            KeyCode::Three => b"3".to_vec(),
            KeyCode::Four => b"4".to_vec(),
            KeyCode::Five => b"5".to_vec(),
            KeyCode::Six => b"6".to_vec(),
            KeyCode::Seven => b"7".to_vec(),
            KeyCode::Eight => b"8".to_vec(),
            KeyCode::Nine => b"9".to_vec(),
            KeyCode::Colon => b":".to_vec(),
            KeyCode::Semicolon => b";".to_vec(),
            KeyCode::LessThan => b"<".to_vec(),
            KeyCode::Equal => b"=".to_vec(),
            KeyCode::GreaterThan => b">".to_vec(),
            KeyCode::Question => b"?".to_vec(),
            KeyCode::At => b"@".to_vec(),
            KeyCode::UpperA => b"A".to_vec(),
            KeyCode::UpperB => b"B".to_vec(),
            KeyCode::UpperC => b"C".to_vec(),
            KeyCode::UpperD => b"D".to_vec(),
            KeyCode::UpperE => b"E".to_vec(),
            KeyCode::UpperF => b"F".to_vec(),
            KeyCode::UpperG => b"G".to_vec(),
            KeyCode::UpperH => b"H".to_vec(),
            KeyCode::UpperI => b"I".to_vec(),
            KeyCode::UpperJ => b"J".to_vec(),
            KeyCode::UpperK => b"K".to_vec(),
            KeyCode::UpperL => b"L".to_vec(),
            KeyCode::UpperM => b"M".to_vec(),
            KeyCode::UpperN => b"N".to_vec(),
            KeyCode::UpperO => b"O".to_vec(),
            KeyCode::UpperP => b"P".to_vec(),
            KeyCode::UpperQ => b"Q".to_vec(),
            KeyCode::UpperR => b"R".to_vec(),
            KeyCode::UpperS => b"S".to_vec(),
            KeyCode::UpperT => b"T".to_vec(),
            KeyCode::UpperU => b"U".to_vec(),
            KeyCode::UpperV => b"V".to_vec(),
            KeyCode::UpperW => b"W".to_vec(),
            KeyCode::UpperX => b"X".to_vec(),
            KeyCode::UpperY => b"Y".to_vec(),
            KeyCode::UpperZ => b"Z".to_vec(),
            KeyCode::LeftBracket => b"[".to_vec(),
            KeyCode::Backslash => b"\\".to_vec(),
            KeyCode::RightBracket => b"]".to_vec(),
            KeyCode::Caret => b"^".to_vec(),
            KeyCode::Underscore => b"_".to_vec(),
            KeyCode::Grave => b"`".to_vec(),
            KeyCode::LowerA => b"a".to_vec(),
            KeyCode::LowerB => b"b".to_vec(),
            KeyCode::LowerC => b"c".to_vec(),
            KeyCode::LowerD => b"d".to_vec(),
            KeyCode::LowerE => b"e".to_vec(),
            KeyCode::LowerF => b"f".to_vec(),
            KeyCode::LowerG => b"g".to_vec(),
            KeyCode::LowerH => b"h".to_vec(),
            KeyCode::LowerI => b"i".to_vec(),
            KeyCode::LowerJ => b"j".to_vec(),
            KeyCode::LowerK => b"k".to_vec(),
            KeyCode::LowerL => b"l".to_vec(),
            KeyCode::LowerM => b"m".to_vec(),
            KeyCode::LowerN => b"n".to_vec(),
            KeyCode::LowerO => b"o".to_vec(),
            KeyCode::LowerP => b"p".to_vec(),
            KeyCode::LowerQ => b"q".to_vec(),
            KeyCode::LowerR => b"r".to_vec(),
            KeyCode::LowerS => b"s".to_vec(),
            KeyCode::LowerT => b"t".to_vec(),
            KeyCode::LowerU => b"u".to_vec(),
            KeyCode::LowerV => b"v".to_vec(),
            KeyCode::LowerW => b"w".to_vec(),
            KeyCode::LowerX => b"x".to_vec(),
            KeyCode::LowerY => b"y".to_vec(),
            KeyCode::LowerZ => b"z".to_vec(),
            KeyCode::LeftBrace => b"{".to_vec(),
            KeyCode::Pipe => b"|".to_vec(),
            KeyCode::RightBrace => b"}".to_vec(),
            KeyCode::Tilde => b"~".to_vec(),
            KeyCode::Del => b"\x7F".to_vec(),
        }
    }

    pub fn from_ascii(value: u8) -> Option<KeyCode> {
        match value {
            0 => Some(KeyCode::Nul),
            1 => Some(KeyCode::Soh),
            2 => Some(KeyCode::Stx),
            3 => Some(KeyCode::Etx),
            4 => Some(KeyCode::Eot),
            5 => Some(KeyCode::Enq),
            6 => Some(KeyCode::Ack),
            7 => Some(KeyCode::Bell),
            8 => Some(KeyCode::Backspace),
            9 => Some(KeyCode::Tab),
            10 => Some(KeyCode::LineFeed),
            11 => Some(KeyCode::Vt),
            12 => Some(KeyCode::Ff),
            13 => Some(KeyCode::CarriageReturn),
            14 => Some(KeyCode::So),
            15 => Some(KeyCode::Si),
            16 => Some(KeyCode::Dle),
            17 => Some(KeyCode::Dc1),
            18 => Some(KeyCode::Dc2),
            19 => Some(KeyCode::Dc3),
            20 => Some(KeyCode::Dc4),
            21 => Some(KeyCode::Nak),
            22 => Some(KeyCode::Syn),
            23 => Some(KeyCode::Etb),
            24 => Some(KeyCode::Can),
            25 => Some(KeyCode::Em),
            26 => Some(KeyCode::Sub),
            27 => Some(KeyCode::Esc),
            28 => Some(KeyCode::Fs),
            29 => Some(KeyCode::Gs),
            30 => Some(KeyCode::Rs),
            31 => Some(KeyCode::Us),
            32 => Some(KeyCode::Space),
            33 => Some(KeyCode::Exclamation),
            34 => Some(KeyCode::DoubleQuote),
            35 => Some(KeyCode::Hash),
            36 => Some(KeyCode::Dollar),
            37 => Some(KeyCode::Percent),
            38 => Some(KeyCode::Ampersand),
            39 => Some(KeyCode::Quote),
            40 => Some(KeyCode::LeftParenthesis),
            41 => Some(KeyCode::RightParenthesis),
            42 => Some(KeyCode::Asterisk),
            43 => Some(KeyCode::Plus),
            44 => Some(KeyCode::Comma),
            45 => Some(KeyCode::Minus),
            46 => Some(KeyCode::Period),
            47 => Some(KeyCode::Slash),
            48 => Some(KeyCode::Zero),
            49 => Some(KeyCode::One),
            50 => Some(KeyCode::Two),
            51 => Some(KeyCode::Three),
            52 => Some(KeyCode::Four),
            53 => Some(KeyCode::Five),
            54 => Some(KeyCode::Six),
            55 => Some(KeyCode::Seven),
            56 => Some(KeyCode::Eight),
            57 => Some(KeyCode::Nine),
            58 => Some(KeyCode::Colon),
            59 => Some(KeyCode::Semicolon),
            60 => Some(KeyCode::LessThan),
            61 => Some(KeyCode::Equal),
            62 => Some(KeyCode::GreaterThan),
            63 => Some(KeyCode::Question),
            64 => Some(KeyCode::At),
            65 => Some(KeyCode::UpperA),
            66 => Some(KeyCode::UpperB),
            67 => Some(KeyCode::UpperC),
            68 => Some(KeyCode::UpperD),
            69 => Some(KeyCode::UpperE),
            70 => Some(KeyCode::UpperF),
            71 => Some(KeyCode::UpperG),
            72 => Some(KeyCode::UpperH),
            73 => Some(KeyCode::UpperI),
            74 => Some(KeyCode::UpperJ),
            75 => Some(KeyCode::UpperK),
            76 => Some(KeyCode::UpperL),
            77 => Some(KeyCode::UpperM),
            78 => Some(KeyCode::UpperN),
            79 => Some(KeyCode::UpperO),
            80 => Some(KeyCode::UpperP),
            81 => Some(KeyCode::UpperQ),
            82 => Some(KeyCode::UpperR),
            83 => Some(KeyCode::UpperS),
            84 => Some(KeyCode::UpperT),
            85 => Some(KeyCode::UpperU),
            86 => Some(KeyCode::UpperV),
            87 => Some(KeyCode::UpperW),
            88 => Some(KeyCode::UpperX),
            89 => Some(KeyCode::UpperY),
            90 => Some(KeyCode::UpperZ),
            91 => Some(KeyCode::LeftBracket),
            92 => Some(KeyCode::Backslash),
            93 => Some(KeyCode::RightBracket),
            94 => Some(KeyCode::Caret),
            95 => Some(KeyCode::Underscore),
            96 => Some(KeyCode::Grave),
            97 => Some(KeyCode::LowerA),
            98 => Some(KeyCode::LowerB),
            99 => Some(KeyCode::LowerC),
            100 => Some(KeyCode::LowerD),
            101 => Some(KeyCode::LowerE),
            102 => Some(KeyCode::LowerF),
            103 => Some(KeyCode::LowerG),
            104 => Some(KeyCode::LowerH),
            105 => Some(KeyCode::LowerI),
            106 => Some(KeyCode::LowerJ),
            107 => Some(KeyCode::LowerK),
            108 => Some(KeyCode::LowerL),
            109 => Some(KeyCode::LowerM),
            110 => Some(KeyCode::LowerN),
            111 => Some(KeyCode::LowerO),
            112 => Some(KeyCode::LowerP),
            113 => Some(KeyCode::LowerQ),
            114 => Some(KeyCode::LowerR),
            115 => Some(KeyCode::LowerS),
            116 => Some(KeyCode::LowerT),
            117 => Some(KeyCode::LowerU),
            118 => Some(KeyCode::LowerV),
            119 => Some(KeyCode::LowerW),
            120 => Some(KeyCode::LowerX),
            121 => Some(KeyCode::LowerY),
            122 => Some(KeyCode::LowerZ),
            123 => Some(KeyCode::LeftBrace),
            124 => Some(KeyCode::Pipe),
            125 => Some(KeyCode::RightBrace),
            126 => Some(KeyCode::Tilde),
            127 => Some(KeyCode::Del),
            _ => None,
        }
    }
}
