[package]
name = "proc-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
default = ["std"]
std = []

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
