repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Cargo fmt (auto-format)
        entry: cargo
        args: [fmt, --all]
        language: system
        pass_filenames: false
        files: \.rs$

      - id: cargo-fix
        name: Cargo fix (auto-fix compiler)
        entry: rustup
        args: [run, nightly, cargo, fix, --workspace, --all-features, --allow-dirty]
        language: system
        pass_filenames: false
        files: \.rs$

      - id: cargo-clippy-fix
        name: Cargo clippy --fix (auto-fix Clippy)
        entry: rustup
        args:
          - run
          - nightly
          - cargo
          - clippy
          - --workspace
          - --all-targets
          - --all-features
          - --fix
          - --allow-dirty
          - --
          - -D
          - warnings
          - -A
          - dead_code
          - -A
          - clippy::module-inception
          - -A
          - clippy::uninlined-format-args
          - -A
          - clippy::missing-safety-doc
        language: system
        pass_filenames: false
        files: \.rs$

      - id: cargo-clippy
        name: Cargo clippy (strict check)
        entry: rustup
        args:
          - run
          - nightly
          - cargo
          - clippy
          - --workspace
          - --all-targets
          - --all-features
          - --
          - -D
          - warnings
          - -A
          - dead_code
          - -A
          - clippy::module-inception
          - -A
          - clippy::uninlined-format-args
          - -A
          - clippy::missing-safety-doc
        language: system
        pass_filenames: false
        files: \.rs$
