[package]
name = "ryvex"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [".", "ryvex-os"]

[profile.dev]
incremental = true
opt-level = 2

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3

[dependencies]
ryvex-os = { path = "ryvex-os" }
