[package]
name = "ryvex-term"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
ryvex-ui = { path = "../ryvex-ui" }
ryvex-tui = { path = "../ryvex-tui" }
proc-macros = { path = "../proc-macros" }
