[package]
name = "ryvex-tui"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = ["std"]
std = []

[dependencies]
ryvex-ui.workspace = true
ryvex-target.workspace = true
