[package]
name = "ryvex-tui"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
ryvex-ui = { path = "../ryvex-ui" }
ryvex-term = { path = "../ryvex-term" }
proc-macros = { path = "../proc-macros"}
